<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <title>Turno Reservado</title>
</head>
<body>
    <div class="container mt-5 text-center">
        <h1>¡Tu turno ha sido reservado con éxito!</h1>
        <p>Gracias por confiar en nosotros.</p>
        <a href="/TurnosLeo/index.php?action=reservar" class="btn btn-primary">Volver al Inicio</a>
    </div>
</body>
</html>
