<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">

    <title>Dream Study</title>
    <style>
        body {
            background-image: url(img/marmol.avif);
            background-size: cover; 
            margin: 0; 
            height: 100vh; 
            font-family: 'Poppins', sans-serif; /* Aplica la fuente Poppins al cuerpo */
        }
        /* Otros estilos... */
        .form-label {
            color: white;
            font-family: 'Poppins', sans-serif; /* Cambia a Poppins */
        }
        .titulo-form,
        .subtitulo-form {
            color: white;
            font-family: 'Poppins', sans-serif; /* Cambia a Poppins */
        }
        .form-control, .form-select {
            font-family: 'Poppins', sans-serif; /* Cambia a Poppins */
        }
        #btn-reservar {
            font-family: 'Poppins', sans-serif; /* Cambia a Poppins */
        }
    </style>
</head>
<body>
    <div class="logo-inicio">
        <img class="logo" src="img/ad9e70e4d5a51fad8bbd7fbed378244a~c5_720x720.jpg" alt="Dream Study">
    </div>

    <div class="contenedor-form">
        <form method="POST" action="index.php?action=add">
            <fieldset>
                <div class="contenedor-titulo">
                    <h1 class="titulo-form"><i class="bi bi-calendar4-week"></i> Turnos</h1>
                </div>
                <div class="mb-3">
                    <h2 class="subtitulo-form">Tus datos</h2>
                    <div class="input-datos">
                        <div class="input-nombre">
                            <label for="nombre" class="form-label">Nombre</label>
                            <input type="text" id="nombre" name="nombre" class="form-control" placeholder="Ingrese su nombre" required>
                        </div>
                        <div class="input-apellido">
                            <label for="apellido" class="form-label">Apellido</label>
                            <input type="text" id="apellido" name="apellido" class="form-control" placeholder="Ingrese su apellido" required>
                        </div>
                    </div>
                    <div class="input-contacto">
                        <div class="input-contacto">
                            <label for="telefono" class="form-label">Teléfono-Celular</label>
                            <input type="text" id="telefono" name="telefono" class="form-control" placeholder="Ingrese su número de teléfono-celular" required>
                        </div>
                        <div class="input-contacto">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" id="email" name="email" class="form-control" placeholder="Ingrese su email" required>
                        </div>
                    </div>
                </div>
                <h2 class="subtitulo-form">Reservar</h2>
                <div class="mb-3">
                    <label for="servicio" class="form-label">Servicio</label>
                    <select id="servicio" name="servicio" class="form-select" required>
                        <option>Corte</option>
                        <option>Corte y barba</option>
                        <option>Corte, barba y cejas</option>
                        <option>Cejas</option>
                    </select>
                    <div class="input-datos-reserva">
                        <div class="input-reserva">
                            <label for="fecha" class="form-label">Fecha</label>
                            <input type="date" id="fecha" name="fecha" class="form-control" required>
                        </div>
                        <div class="input-reserva">
                            <label for="horario" class="form-label">Horario</label>
                            <select id="horario" name="horario" class="form-select" required>
                                <option value="">-- Selecciona un horario --</option>
                                <!-- Las opciones se llenarán aquí mediante JavaScript -->
                            </select>
                        </div>
                    </div>

                </div>
                <div class="contenedor-btn-reserva">
                    <button type="submit" id="btn-reservar" class="btn btn-primary">Reservar</button>
                </div>
            </fieldset>
        </form>
    </div>
    <footer class="text-center">
        <div class="container footer-content">
            <div class="footer-logo-social">
                <div class="social-icons">
                    <a href="https://instagram.com" target="_blank" class="bi bi-instagram"></a>
                    <a href="https://tiktok.com" target="_blank" class="bi bi-tiktok"></a>
                </div>
            </div>
            <p class="m-0">“La belleza comienza en el momento en que decides ser tú mismo.”</p>
            <small class="m-0">Desarrollado por Enzo Jatip</small>
        </div>
    </footer>
    <script src="./js/app.js"></script>
</body>
</html>  